# Generated by Django 4.2.7 on 2024-01-31 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('okladka', models.ImageField(blank=True, null=True, upload_to='okladki/')),
                ('cena', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('data_utworzenia', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('kategorie', models.ManyToManyField(to='mainapp.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Zakladka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ksiazka')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
