# Generated by Django 4.2.7 on 2024-02-14 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('okladka', models.ImageField(blank=True, null=True, upload_to='okladki/')),
                ('cena', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('data_utworzenia', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data utworzenia')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.autor')),
                ('kategorie', models.ManyToManyField(to='mainapp.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Wydawnictwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZakupionaKsiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zakupu', models.DateTimeField(auto_now_add=True)),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ksiazka')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zakladka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ksiazka')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrzegladanaKsiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_przegladania', models.DateTimeField(auto_now_add=True)),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ksiazka')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUzytkownika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(blank=True, max_length=255)),
                ('kod_pocztowy', models.CharField(blank=True, max_length=10)),
                ('miasto', models.CharField(blank=True, max_length=100)),
                ('wojewodztwo', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='wydawnictwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.wydawnictwo'),
        ),
    ]
