# Generated by Django 4.2.7 on 2023-11-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('okladka', models.ImageField(blank=True, null=True, upload_to='okaldki/')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
