# Generated by Django 4.2.7 on 2024-02-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_autor_wydawnictwo_ksiazka_wydawnictwo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wydawnictwo',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
