# Generated by Django 4.2.7 on 2023-11-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_ksiazka_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ksiazka',
            name='okladka',
            field=models.ImageField(blank=True, null=True, upload_to='okladki/'),
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='kategorie',
            field=models.ManyToManyField(to='mainapp.kategoria'),
        ),
    ]
