# Generated by Django 4.2.7 on 2024-02-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_zamowienie_pozycjazamowienia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycjazamowienia',
            name='ilosc',
            field=models.PositiveIntegerField(default=1, verbose_name='Ilość'),
            preserve_default=False,
        ),
    ]
