# Generated by Django 4.2.7 on 2024-02-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_pozycjazamowienia_ilosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='adres',
            field=models.CharField(default='nazwa', max_length=255, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='kod_pocztowy',
            field=models.CharField(default='111', max_length=10, verbose_name='Kod pocztowy'),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='miasto',
            field=models.CharField(default='nazwa', max_length=100, verbose_name='Miasto'),
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='wojewodztwo',
            field=models.CharField(default='nazwa', max_length=100, verbose_name='Województwo'),
        ),
    ]
