# Generated by Django 4.2.7 on 2024-02-03 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_wydawnictwo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='wydawnictwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.wydawnictwo'),
        ),
    ]
