# Generated by Django 4.2.7 on 2024-02-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_zamowienie_adres_zamowienie_kod_pocztowy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakupionaksiazka',
            name='ksiazka',
        ),
        migrations.RemoveField(
            model_name='zakupionaksiazka',
            name='uzytkownik',
        ),
        migrations.DeleteModel(
            name='PrzegladanaKsiazka',
        ),
        migrations.DeleteModel(
            name='ZakupionaKsiazka',
        ),
    ]
