# Generated by Django 4.2.7 on 2024-02-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_zakupionaksiazka_przegladanaksiazka'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoria',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
