# Generated by Django 4.2.7 on 2024-02-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_przegladaneksiazki'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycjazamowienia',
            name='ksiazka',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.ksiazka', verbose_name='Książka'),
        ),
    ]
