# Generated by Django 4.2.7 on 2024-02-17 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_pozycjazamowienia_ksiazka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pozycjazamowienia',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='pozycjazamowienia',
            name='tytul',
        ),
    ]
