# Generated by Django 4.2.7 on 2024-02-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_pozycjazamowienia_ksiazka'),
    ]

    operations = [
        migrations.AddField(
            model_name='pozycjazamowienia',
            name='autor',
            field=models.CharField(default='nazwa', max_length=200, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='pozycjazamowienia',
            name='tytul',
            field=models.CharField(default='nazwa', max_length=200, verbose_name='Tytuł książki'),
        ),
    ]
