# Generated by Django 4.2.7 on 2024-02-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_remove_pozycjazamowienia_autor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zakladka',
        ),
    ]
