# Generated by Django 4.2.7 on 2024-03-04 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_zakladka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autorzy'},
        ),
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='wydawnictwo',
            options={'verbose_name': 'Wydawnictwo', 'verbose_name_plural': 'Wydawnictwa'},
        ),
    ]
