# Generated by Django 4.2.7 on 2024-03-04 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_alter_autor_options_alter_kategoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ksiazka',
            options={'verbose_name': 'Ksiażka', 'verbose_name_plural': 'Książki'},
        ),
    ]
