# Generated by Django 4.2.7 on 2024-04-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_ksiazka_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksiazka',
            name='dostepnosc',
            field=models.CharField(choices=[('dostępna', 'Dostępna'), ('niedostępna', 'Niedostępna'), ('na_zamówienie', 'Na zamówienie')], default='dostępna', max_length=15, verbose_name='Dostępność'),
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='ocena',
            field=models.FloatField(blank=True, null=True, verbose_name='Ocena'),
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='typ_okladki',
            field=models.CharField(choices=[('twarda', 'Twarda'), ('miekką', 'Miękka')], default='miekką', max_length=10, verbose_name='Typ okładki'),
        ),
    ]
