# Generated by Django 4.2.7 on 2024-04-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_ksiazka_dostepnosc_ksiazka_ocena_ksiazka_typ_okladki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ksiazka',
            name='data_utworzenia',
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='rok_wydania',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rok wydania'),
        ),
    ]
