# Generated by Django 4.2.7 on 2024-04-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_remove_ksiazka_data_utworzenia_ksiazka_rok_wydania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ksiazka',
            name='ocena',
        ),
    ]
