# Generated by Django 4.2.7 on 2024-04-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_remove_ksiazka_ocena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='dostepnosc',
            field=models.CharField(choices=[('dostępna', 'Dostępna'), ('niedostępna', 'Niedostępna')], default='dostępna', max_length=15, verbose_name='Dostępność'),
        ),
    ]
