# Generated by Django 4.2.7 on 2024-04-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_alter_ksiazka_dostepnosc'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='wyslano',
            field=models.BooleanField(default=False, verbose_name='Wysłano książki'),
        ),
    ]
