# Generated by Django 4.2.7 on 2024-04-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_zamowienie_wyslano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='typ_okladki',
            field=models.CharField(blank=True, choices=[('twarda', 'Twarda'), ('miekką', 'Miękka')], max_length=10, null=True, verbose_name='Typ okładki'),
        ),
    ]
